import sys

from PyQt5 import QtWidgets
from PyQt5 import QtCore
from PyQt5 import QtGui
from PyQt5.QtWidgets import QTableWidgetItem, QAbstractItemView, QFrame


class DisplayWidget(QtWidgets.QWidget):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.layout = QtWidgets.QHBoxLayout()
        self.setLayout(self.layout)

        self.frame = QtWidgets.QFrame()

        self.frame.setGeometry(QtCore.QRect(20, 40, 1241, 511))
        self.frame.setMinimumSize(QtCore.QSize(1241, 511))
        self.frame.setMaximumSize(QtCore.QSize(1241, 511))
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(4)
        self.frame.setMidLineWidth(0)
        self.frame.setObjectName("frame")


        self.layout.addWidget(self.frame)

        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(30, 30, 30, 30)
        self.horizontalLayout.setSpacing(30)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.frame)
        self.scrollArea_2.setStyleSheet("background-color: rgb(225, 225, 225);\n"
                                        "")
        self.scrollArea_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.scrollArea_2.setLineWidth(4)
        self.scrollArea_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 568, 435))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.scrollAreaWidgetContents_2)
        self.scrollArea.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Panel)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.scrollArea.setLineWidth(4)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 460, 405))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tableWidget = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("background-color: rgb(239, 239, 239);\n"
                                       "font: 9pt \"Consolas\";")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setTabKeyNavigation(False)
        self.tableWidget.setProperty("showDropIndicator", True)
        self.tableWidget.setDragEnabled(False)
        self.tableWidget.setDragDropOverwriteMode(True)
        self.tableWidget.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tableWidget.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setIconSize(QtCore.QSize(0, 0))
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)

        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(130)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(49)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(40)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setMinimumSectionSize(40)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_4.addWidget(self.tableWidget)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.addWidget(self.scrollArea)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(10, -1, 10, -1)
        self.verticalLayout.setSpacing(38)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pb_edit_chunk = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pb_edit_chunk.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.pb_edit_chunk.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Downloads/free-icon-editing-3388936.png"), QtGui.QIcon.Normal,
                       QtGui.QIcon.Off)
        self.pb_edit_chunk.setIcon(icon)
        self.pb_edit_chunk.setIconSize(QtCore.QSize(38, 38))
        self.pb_edit_chunk.setObjectName("pb_edit_chunk")
        self.verticalLayout.addWidget(self.pb_edit_chunk, 0, QtCore.Qt.AlignBottom)
        self.pb_del_chunk = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pb_del_chunk.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.pb_del_chunk.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("trash-can.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.pb_del_chunk.setIcon(icon1)
        self.pb_del_chunk.setIconSize(QtCore.QSize(38, 38))
        self.pb_del_chunk.setObjectName("pb_del_chunk")
        self.verticalLayout.addWidget(self.pb_del_chunk, 0, QtCore.Qt.AlignTop)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout.addWidget(self.scrollArea_2)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.frame)
        self.scrollArea_3.setStyleSheet("\n"
                                        "background-color: rgb(225, 225, 225);")
        self.scrollArea_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.scrollArea_3.setLineWidth(4)
        self.scrollArea_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 559, 435))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.scrollAreaWidgetContents_3)
        self.scrollArea_4.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.scrollArea_4.setFrameShape(QtWidgets.QFrame.Panel)
        self.scrollArea_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.scrollArea_4.setLineWidth(4)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 451, 405))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        self.tableWidget_2.setFont(font)
        self.tableWidget_2.setStyleSheet("background-color: rgb(239, 239, 239);\n"
                                         "font: 9pt \"Consolas\";")
        self.tableWidget_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget_2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_2.setTabKeyNavigation(False)
        self.tableWidget_2.setProperty("showDropIndicator", True)
        self.tableWidget_2.setDragEnabled(False)
        self.tableWidget_2.setDragDropOverwriteMode(True)
        self.tableWidget_2.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_2.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_2.setTextElideMode(QtCore.Qt.ElideRight)
        self.tableWidget_2.setWordWrap(True)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(4)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()

        self.tableWidget_2.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_2.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)

        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 2, item)
        self.tableWidget_2.horizontalHeader().setVisible(True)
        self.tableWidget_2.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(130)
        self.tableWidget_2.horizontalHeader().setHighlightSections(True)
        self.tableWidget_2.horizontalHeader().setMinimumSectionSize(49)
        self.tableWidget_2.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_2.verticalHeader().setVisible(True)
        self.tableWidget_2.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget_2.verticalHeader().setDefaultSectionSize(40)
        self.tableWidget_2.verticalHeader().setHighlightSections(True)
        self.tableWidget_2.verticalHeader().setMinimumSectionSize(40)
        self.tableWidget_2.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget_2.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout_4.addWidget(self.tableWidget_2)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.horizontalLayout_3.addWidget(self.scrollArea_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(10, -1, 10, -1)
        self.verticalLayout_2.setSpacing(38)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.pb_edit_test = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pb_edit_test.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.pb_edit_test.setText("")
        self.pb_edit_test.setIcon(icon)
        self.pb_edit_test.setIconSize(QtCore.QSize(38, 38))
        self.pb_edit_test.setObjectName("pb_edit_test")
        self.verticalLayout_2.addWidget(self.pb_edit_test, 0, QtCore.Qt.AlignBottom)
        self.pb_add_test = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pb_add_test.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.pb_add_test.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../Downloads/icons8-плюс-78 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_add_test.setIcon(icon2)
        self.pb_add_test.setIconSize(QtCore.QSize(38, 38))
        self.pb_add_test.setObjectName("pb_add_test")
        self.verticalLayout_2.addWidget(self.pb_add_test)
        self.pb_del_test = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pb_del_test.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.pb_del_test.setText("")
        self.pb_del_test.setIcon(icon1)
        self.pb_del_test.setIconSize(QtCore.QSize(38, 38))
        self.pb_del_test.setObjectName("pb_del_test")
        self.verticalLayout_2.addWidget(self.pb_del_test, 0, QtCore.Qt.AlignTop)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.horizontalLayout.addWidget(self.scrollArea_3)
        self.retranslateUi()

        self.tableWidget_2.horizontalHeaderItem(3)
        self.tableWidget_2.horizontalHeaderItem(4)

        self.tableWidget_2.setHorizontalHeaderItem(2, QTableWidgetItem("Ответ"))
        self.tableWidget_2.setHorizontalHeaderItem(3, QTableWidgetItem("Баллы"))

        afont = QtGui.QFont()
        afont.setFamily("Consolas")
        afont.setPointSize(9)
        afont.setBold(True)
        self.tableWidget_2.horizontalHeaderItem(2).setFont(afont)
        self.tableWidget_2.horizontalHeaderItem(3).setFont(afont)

        self.tableWidget.setSelectionMode(QAbstractItemView.NoSelection)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)

        self.tableWidget.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Fixed)


    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("test", "1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("test", "Ограничение"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("test", "Необходимая группа"))

        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("test", "sdfds"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("test", ""))

        self.tableWidget.setSortingEnabled(__sortingEnabled)
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("test", "Имя файла"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("test", "Тестовые\nданные"))

        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)

        self.tableWidget_2.setSortingEnabled(__sortingEnabled)




        self.frame.setStyleSheet("background: #546D79;"
                                 "border-top-left-radius: 5px;"
                                 " border-bottom-left-radius: 5px;"
                                 "border-bottom-right-radius: 5px;"
                                 "border-top-right-radius: 5px;")

        self.tableWidget.setStyleSheet("""
            QTableWidget::item {padding-left: 5px;
             border: 0px;
              padding-top: 5px;
              padding-bottom: 5px;
              padding-left: 5px;
              padding-right: 5px}
            """)
        self.tableWidget_2.setStyleSheet("""
                    QTableWidget::item {padding-left: 5px;
                     
                      padding-top: 5px;
                      padding-bottom: 5px;
                      padding-left: 5px;
                      padding-right: 5px}
                    """)


        self.pb_del_chunk.setStyleSheet("border: 2px solid #90A4AE")
        self.pb_edit_chunk.setStyleSheet("border: 2px solid #90A4AE")
        self.pb_del_test.setStyleSheet("border: 2px solid #90A4AE")
        self.pb_edit_test.setStyleSheet("border: 2px solid #90A4AE")
        self.pb_add_test.setStyleSheet("border: 2px solid #90A4AE")
        self.pb_del_chunk.setFixedSize(50,50)
        self.pb_del_test.setFixedSize(50,50)
        self.pb_edit_test.setFixedSize(50,50)
        self.pb_edit_chunk.setFixedSize(50,50)
        self.pb_add_test.setFixedSize(50,50)

        self.tableWidget_2.resizeColumnToContents(0)
        self.tableWidget_2.resizeColumnToContents(3)
        self.tableWidget_2.resizeRowsToContents()

        self.tableWidget.setColumnWidth(0, 210)
        self.tableWidget.resizeRowsToContents()







'''class MainWindow(QtWidgets.QMainWindow):

    def __init__(self, parent=None):
        super().__init__(parent)
        self.init_gui()

    def init_gui(self):
        self.window = QtWidgets.QWidget()
        self.layout = QtWidgets.QGridLayout()
        self.setCentralWidget(self.window)
        self.window.setLayout(self.layout)

        self.echotext_widget = EchoText()
        self.echotext_widget1 = EchoText()

        self.layout.addWidget(self.echotext_widget)
        self.layout.addWidget(self.echotext_widget1)



if __name__ == '__main__':
    app = QtWidgets.QApplication([])

    win = MainWindow()
    win.show()

    sys.exit(app.exec_())'''