# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'genjson.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form2(object):
    def setupUi(self, Form2):
        Form2.setObjectName("Form2")
        Form2.resize(1025, 747)
        Form2.setMinimumSize(QtCore.QSize(1025, 747))
        Form2.setMaximumSize(QtCore.QSize(1025, 747))
        self.layoutWidget = QtWidgets.QWidget(Form2)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 1021, 741))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(50, 0, 50, 0)
        self.horizontalLayout_2.setSpacing(30)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.add_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.add_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_2.sizePolicy().hasHeightForWidth())
        self.add_2.setSizePolicy(sizePolicy)
        self.add_2.setMaximumSize(QtCore.QSize(500, 80))
        self.add_2.setSizeIncrement(QtCore.QSize(0, 0))
        self.add_2.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Consolas 12")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.add_2.setFont(font)
        self.add_2.setTabletTracking(False)
        self.add_2.setAcceptDrops(False)
        self.add_2.setToolTip("")
        self.add_2.setToolTipDuration(-1)
        self.add_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.add_2.setAutoFillBackground(False)
        self.add_2.setStyleSheet("QPushButton {\n"
"        background-color: #F0F0F0;\n"
"        border: 5px solid #B5B5B5; \n"
"        border-radius: 10px; \n"
"        padding: 6px;\n"
"        font: 28pt \"Consolas\" bold;\n"
"    \n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: #DADADA;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        background-color: #919191;\n"
"    }")
        self.add_2.setCheckable(False)
        self.add_2.setObjectName("add_2")
        self.horizontalLayout_2.addWidget(self.add_2)
        self.open_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.open_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_2.sizePolicy().hasHeightForWidth())
        self.open_2.setSizePolicy(sizePolicy)
        self.open_2.setMaximumSize(QtCore.QSize(500, 80))
        self.open_2.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Consolas 12")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.open_2.setFont(font)
        self.open_2.setTabletTracking(False)
        self.open_2.setAcceptDrops(False)
        self.open_2.setToolTipDuration(-1)
        self.open_2.setAutoFillBackground(False)
        self.open_2.setStyleSheet("QPushButton {\n"
"        background-color: #F0F0F0;\n"
"        border: 5px solid #B5B5B5; \n"
"        border-radius: 10px; \n"
"        padding: 6px;\n"
"        font: 28pt \"Consolas\" bold;\n"
"    \n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: #DADADA;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        background-color: #919191;\n"
"    }")
        self.open_2.setObjectName("open_2")
        self.horizontalLayout_2.addWidget(self.open_2)

        self.retranslateUi(Form2)
        QtCore.QMetaObject.connectSlotsByName(Form2)

    def retranslateUi(self, Form2):
        _translate = QtCore.QCoreApplication.translate
        Form2.setWindowTitle(_translate("Form2", "Form"))
        self.add_2.setText(_translate("Form2", "Создать"))
        self.open_2.setText(_translate("Form2", "Открыть"))
