# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'list_of_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_list_of_test(object):
    def setupUi(self, list_of_test):
        list_of_test.setObjectName("list_of_test")
        list_of_test.resize(934, 719)
        list_of_test.setMinimumSize(QtCore.QSize(934, 719))
        list_of_test.setMaximumSize(QtCore.QSize(934, 719))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(list_of_test)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(list_of_test)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 910, 695))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_4.setSpacing(20)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 67))
        self.label.setMaximumSize(QtCore.QSize(16777215, 67))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(25)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 25pt \"Consolas\";\n"
"padding-top: 20 px;\n"
"padding-left: 0 px;")
        self.label.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.pushb_1_add = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushb_1_add.sizePolicy().hasHeightForWidth())
        self.pushb_1_add.setSizePolicy(sizePolicy)
        self.pushb_1_add.setMinimumSize(QtCore.QSize(137, 0))
        self.pushb_1_add.setMaximumSize(QtCore.QSize(180, 29))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushb_1_add.setFont(font)
        self.pushb_1_add.setStyleSheet("font: 10pt \"Consolas\";")
        self.pushb_1_add.setFlat(False)
        self.pushb_1_add.setObjectName("pushb_1_add")
        self.verticalLayout_4.addWidget(self.pushb_1_add)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_2.setVerticalSpacing(11)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        self.verticalLayout_2.addWidget(self.widget, 0, QtCore.Qt.AlignTop)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)

        self.retranslateUi(list_of_test)
        QtCore.QMetaObject.connectSlotsByName(list_of_test)

    def retranslateUi(self, list_of_test):
        _translate = QtCore.QCoreApplication.translate
        list_of_test.setWindowTitle(_translate("list_of_test", "Form"))
        self.label.setText(_translate("list_of_test", "Примеры из условия:"))
        self.pushb_1_add.setText(_translate("list_of_test", "Добавить"))
