# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'list_of_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_list_of_test(object):
    def setupUi(self, list_of_test):
        list_of_test.setObjectName("list_of_test")
        list_of_test.resize(1350, 800)
        list_of_test.setMinimumSize(QtCore.QSize(1350, 800))
        list_of_test.setMaximumSize(QtCore.QSize(1350, 800))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(list_of_test)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(list_of_test)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 200))
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1326, 776))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(20, -1, -1, -1)
        self.verticalLayout_5.setSpacing(25)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 67))
        self.label.setMaximumSize(QtCore.QSize(16777215, 67))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(25)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 25pt \"Consolas\";\n"
"padding-top: 20 px;\n"
"padding-left: 0 px;")
        self.label.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label, 0, QtCore.Qt.AlignTop)
        self.pushb_1_add = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushb_1_add.sizePolicy().hasHeightForWidth())
        self.pushb_1_add.setSizePolicy(sizePolicy)
        self.pushb_1_add.setMinimumSize(QtCore.QSize(137, 0))
        self.pushb_1_add.setMaximumSize(QtCore.QSize(180, 36))
        font = QtGui.QFont()
        font.setFamily("Consolas 12")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushb_1_add.setFont(font)
        self.pushb_1_add.setStyleSheet("QPushButton {\n"
"        background-color: #F0F0F0;\n"
"        border: 3px solid #B5B5B5; \n"
"        border-radius: 10px; \n"
"        padding: 3px;\n"
"        font: 12pt \"Consolas\" bold;\n"
"    \n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: #DADADA;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        background-color: #919191;\n"
"    }")
        self.pushb_1_add.setFlat(False)
        self.pushb_1_add.setObjectName("pushb_1_add")
        self.verticalLayout_5.addWidget(self.pushb_1_add, 0, QtCore.Qt.AlignTop)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout_5)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)

        self.retranslateUi(list_of_test)
        QtCore.QMetaObject.connectSlotsByName(list_of_test)

    def retranslateUi(self, list_of_test):
        _translate = QtCore.QCoreApplication.translate
        list_of_test.setWindowTitle(_translate("list_of_test", "Form"))
        self.label.setText(_translate("list_of_test", "Примеры из условия:"))
        self.pushb_1_add.setText(_translate("list_of_test", "Добавить"))
