# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'necessary_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_necessary_test(object):
    def setupUi(self, necessary_test):
        necessary_test.setObjectName("necessary_test")
        necessary_test.resize(343, 397)
        self.scrollArea = QtWidgets.QScrollArea(necessary_test)
        self.scrollArea.setGeometry(QtCore.QRect(0, 10, 341, 341))
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 341, 341))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.formLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 0, 341, 341))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(119, 15, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.done = QtWidgets.QPushButton(necessary_test)
        self.done.setGeometry(QtCore.QRect(230, 357, 100, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.done.setFont(font)
        self.done.setObjectName("done")

        self.retranslateUi(necessary_test)
        QtCore.QMetaObject.connectSlotsByName(necessary_test)

    def retranslateUi(self, necessary_test):
        _translate = QtCore.QCoreApplication.translate
        necessary_test.setWindowTitle(_translate("necessary_test", "Form"))
        self.done.setText(_translate("necessary_test", "Готово"))
